### ISSUE TITLE
iPod 30-pin to USB-c ~ sale of units?

### ISSUE THREAD

**Issue by raleighlittles** [Suzhou65/Suzhou65.github.io#1]
I came across your awesome Reddit post about the USB-c interface you made for your iPod: https://www.reddit.com/r/ipod/comments/11omsky/usb_typec_to_retro_apple_30pin/

In the post you mentioned they weren't for commercial use, but that was 6 months ago -- have you changed your mind at all? I would love to purchase a completed unit. Something like this would be popular on [Tindie](https://www.tindie.com/) or maybe Etsy even as well, if you'd want to reach a larger audience.

**Comment by Suzhou65** [comment]
Dear raleighlittles,

Apologize for the late reply. Currently, I have no intention of switching to commercial.

The main reason is that circuit design has signal integrity issue, especially with the USB signal, which needs to be a differential pair. I will redesign it.

The second reason is that. I designed the logic board to provide power and digital audio output functions, just like the old Onkyo iPod Docker, but in open source,  the current design needs to be converted into HAT board style.
